version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: embalagem-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod

  postgres:
    image: postgres:15
    container_name: embalagem-postgres
    restart: always
    environment:
      POSTGRES_DB: embalagensdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
